FROM ubuntu:20.04
EXPOSE 6443 80 443 8080 
WORKDIR /src

COPY . .

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y sudo

RUN find /src -exec chmod +x {} \;
RUN sudo /bin/bash -c "/src/kubernetes/createKubernetesCluster.sh true"

# Add an entrypoint script (if needed) to initialize your container
COPY /docker/master-node/entryPoint.sh /usr/local/bin/entryPoint.sh
RUN chmod +x /usr/local/bin/entryPoint.sh

ENTRYPOINT ["/usr/local/bin/entryPoint.sh"]