services:
  eshop-k8s-master:
    hostname: eshop-k8s-master
    container_name: eshop-k8s-master
    image: ${REGISTRY:-eshop}/eshop-k8s-master:latest
    privileged: true
    build:
      context: .
      dockerfile: ./docker/master-node/Dockerfile
    # environment:
    #   - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    #   - K3S_KUBECONFIG_MODE=644
    ports:
      - "6443:6443"
      - "80:80"
      - "443:443"

  # eshop-k8s-worker:
  #   hostname: eshop-k8s-worker
  #   container_name: eshop-k8s-worker
  #   image: ${REGISTRY:-eshop}/eshop-k8s-worker:latest
  #   build:
  #     context: .
  #     dockerfile: ./docker/worker-node/Dockerfile
    
volumes:
  k8s-images:

